services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: parser
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - sqlite_data:/app/db
    command: python app.py
volumes:
  sqlite_data:
    driver: local
